# Generated by Django 5.2.6 on 2025-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='book',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
